4. Numpy 배열의 결합과 변형 
-----
np.concatenate
np.stack
ndarray.reshape
ndarry.transpose

In [2]:
import numpy as np
#np.concatenate()

In [3]:
vec1 = np.arange(0,4)
vec2 = np.arange(4,8)
np.concatenate([vec1,vec2])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
np.concatenate([vec2,vec1])

array([4, 5, 6, 7, 0, 1, 2, 3])

In [5]:
np.concatenate([vec1,[1,2,3,4,5,]])

array([0, 1, 2, 3, 1, 2, 3, 4, 5])

In [6]:
# 2차원 배열 
ary1 = np.arange(0,8).reshape(2,4)
ary2 = np.arange(8,16).reshape(2,4)

In [7]:
np.concatenate([ary1,ary2],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
np.concatenate([ary1,ary2],axis=1)

array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])

In [9]:
ary2[0,:]

array([ 8,  9, 10, 11])

In [12]:
vec1 = ary2[0,:]
print(vec1)

[ 8  9 10 11]


In [16]:
mat1 = vec1[np.newaxis]

mat1.ndim

2

In [17]:
np.concatenate([ary1,mat1],axis =0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
print(ary1)
print(ary2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [22]:
vec1 =ary2[:,0]
vec1.ndim

1

In [23]:

mat1 = vec1[np.newaxis]
mat1.ndim

2

In [24]:
np.concatenate([ary1,mat1], axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [25]:
print(ary2[:,0].shape)
ary2[:,0]

(2,)


array([ 8, 12])

In [26]:
mat1

array([[ 8, 12]])

In [28]:
mat1.T

array([[ 8],
       [12]])

In [29]:
print(mat1.shape)
print(mat1.T.shape)

(1, 2)
(2, 1)


In [30]:
np.concatenate([ary1,mat1.T],axis =1)

array([[ 0,  1,  2,  3,  8],
       [ 4,  5,  6,  7, 12]])

In [31]:
ary1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [32]:
mat1 = np.array([[8,9,10]])


In [33]:
print(ary1.ndim)
print(mat1.ndim)


2
2


In [34]:
np.concatenate([ary1,mat1],axis= 0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [36]:
print(ary1.shape)
print(mat1.shape)
# axis 인자 으 ㅣ축을 제외한 모든 축에서의 원소의 개수가 같아야한다. 



(2, 4)
(1, 3)


In [37]:
ary1.shape

(2, 4)

In [41]:
mat1 = np.array([[8,9,10,11]])
mat1.shape

(1, 4)

In [42]:
np.concatenate([mat1,ary1])

array([[ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

여러 배열의 각 우너소롤 새로운 축만들어 쌓기 np.stack
`
np.stack([ary1,ary2,...], axis= 0)
`
은  
동일한 shape 를 갖는 배열들을 컨테이너 자료형으로 입력받는다 .  
인자로 받은 axis위 치상에서 입력받은 각배열을 하나의 원소로 하여 새로운 축으만든다 .  
반환된 배열의 ndim은 입력받은 차원인 ndim+1이다.  
새롭게 생성된 축에서 원소의 개수는 입력받은 배열의 수이다 .

In [44]:
vec1 = np.arange(0,6)
vec2 = np.arange(6,12)

In [45]:
print(vec1.shape)
print(vec2.shape)

(6,)
(6,)


In [47]:
np.stack([vec1,vec2])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [48]:
np.stack([vec1,vec2]).shape

(2, 6)

In [49]:
ary1 = np.arange(0,12).reshape(3,4)
ary2 = np.arange(12,24).reshape(3,4)

In [50]:
display(ary1)
display(ary2)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [51]:
np.stack([ary1,ary2], axis =0).shape

(2, 3, 4)

In [52]:
print(ary1.shape)
print(ary2.shape)

(3, 4)
(3, 4)


In [53]:
np.stack([ary1,ary2],axis =1 )

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [54]:
np.stack([ary1,ary2],axis=1).shape

(3, 2, 4)

In [56]:
#ary1의 각 원소 ,ary2의 각 원소를 쌓아 2차원으로 원소를 갖는 배열
np.stack([ary1,ary2], axis =2)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [57]:
np.stack([ary1,ary2],axis =2 ).shape

(3, 4, 2)

In [58]:
np.array([ary1,ary2])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [59]:
np.stack([ary1,ary2],axis =1)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [60]:
np.array([ary1,ary2]).reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [65]:
vec1 = np.array([0,1,2,3])
vec1

array([0, 1, 2, 3])

In [66]:
display(np.array([ary1,vec1]))
np.array([ary1,vec1]).shape

array([array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]),
       array([0, 1, 2, 3])], dtype=object)

(2,)

In [67]:
np.stack([ary1,vec1],axis=2)

ValueError: all input arrays must have the same shape

입력되는 배열들의 모양은 모두 동일해야한다. 

In [68]:
display(ary1)
ary3 = ary2[:2]
display(ary3)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [69]:
np.stack([ary1,ary3],axis =0)

ValueError: all input arrays must have the same shape

np.reshape 배열의 모양바꾸기 


In [70]:
#동일한 데이터의 다양한 모양 
display(np.array([0,1,2,3,4,5]))
np.array([0,1,2,3,4,5]).shape
np.array([0,1,2,3,4,5]).size

array([0, 1, 2, 3, 4, 5])

6

In [72]:
np.array([[0,1,2],[3,4,5]])
np.array([[0,1,2],[3,4,5]]).shape

(2, 3)

In [73]:
np.array([[0,1],[2,3],[4,5]])
np.array([[0,1],[2,3],[4,5]]).shape

(3, 2)

In [74]:
vec = np.arange(6)

In [75]:
vec.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
vec.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [77]:
vec.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [79]:
ary = np.array(
    [[[ 0, 1, 2, 3],
      [ 4, 5, 6, 7]],
     [[ 8, 9,10,11],
      [12,13,14,15]],
     [[16,17,18,19],
      [20,21,22,23]]]

)
ary.shape

(3, 2, 4)

In [80]:
ary.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [81]:
ary.reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [82]:
ary.reshape(4,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [83]:
#낮은 차원으로 모양바꾸기 
ary.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [84]:
ary.reshape(2,2,2,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [85]:
#원소의 사이즈는 변함이없어야한다. 
ary = np.arange(0,24)
display(ary)
print(ary.shape)
print(ary.size)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

(24,)
24


In [90]:
display(ary.reshape(3,8))
print(ary.reshape(3,8).size)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

24


In [91]:
# w자동 설정 
ary2 = ary.reshape(2,-1)

In [92]:
ary2.shape

(2, 12)

In [93]:
ary.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

np.transpose  
??np.transpose
배열의 축 인자의 순서대로 바꾼다   
axes인자의 값이 none일 경우 축이 반전된다. 
배열의 원소 갯수와 차원은 바뀌지 않는다 .
원소들의 순서와 위치가 변한다. 
ndarray.T 와 ndarray.transepose(none)은 동일하다.

In [94]:
??np.transpose

In [95]:
vec = np.array([0,1])
vec.shape

(2,)

In [99]:
vec.transpose()

array([0, 1])

In [100]:
mat  = np.arange(6).reshape(2,3)
mat

array([[0, 1, 2],
       [3, 4, 5]])

In [101]:
mat.transpose()
mat.T
transposed_mat = mat.T
transposed_mat

array([[0, 3],
       [1, 4],
       [2, 5]])

In [102]:
print(mat.shape)
print(transposed_mat.shape)

(2, 3)
(3, 2)


In [103]:
display(mat.flatten())
display(transposed_mat.flatten())

array([0, 1, 2, 3, 4, 5])

array([0, 3, 1, 4, 2, 5])

In [104]:
display(mat)
print("transpose 이전 '2'의 위치 : mat[0,2]")
print("--------------------")
display(transposed_mat)
print("Transpose 이후 '2'의 위치 : transposed_mat[2,0]")

array([[0, 1, 2],
       [3, 4, 5]])

transpose 이전 '2'의 위치 : mat[0,2]
--------------------


array([[0, 3],
       [1, 4],
       [2, 5]])

Transpose 이후 '2'의 위치 : transposed_mat[2,0]


In [107]:
ary_3d = np.arange(24).reshape(2,3,4)
ary_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [109]:
# 0,1,2 축이 210으로 바뀜 
ary_3d.transpose()


array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])