# numpy 배열의 인덱싱 
------
dimention axis indexing

In [173]:
import numpy as np

In [174]:
lst = [100,200,400]

In [3]:
lst[2]

400

In [175]:
lst[1]

200

In [4]:
dict1 ={"a":100, "b":300}

In [5]:
dict1["a"]

100

In [6]:
np.array([1,2,3,4,5])[3]

4

In [144]:
ary = np.arange(0,12).reshape(3,4)
ary

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
ary.shape

(3, 4)

In [9]:
#find 6 
#하나씩 접근 합니다.
ary[1][2]

6

In [15]:
# 축을개념으로 가져옵니다. 
ary[1,2]

6

In [165]:
np.ones(()) # 0차원

array(1.)

In [166]:
np.ones((1)) # 1차원

array([1.])

In [169]:
np.ones((1,2)) # 2차원

array([[1., 1.]])

In [135]:
ary[0,0,0]

1.0

In [17]:
ary[0:2,0]

array([0, 4])

In [18]:
ary[0]

array([0, 1, 2, 3])

In [19]:
ary[0][1:3]

array([1, 2])

In [22]:
#[56,910]가져오기
ary[1:3][1:3]

array([[ 8,  9, 10, 11]])

In [23]:
ary[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [30]:
#1,3,5,7,9,11
ary[:,1:4:2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [25]:
ary[:,0:4:2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [27]:
ary[1][:]

array([4, 5, 6, 7])

In [28]:
ary[1,:]

array([4, 5, 6, 7])

In [31]:
ary[:,1]

array([1, 5, 9])

In [33]:
ary

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
ary[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [37]:
ary[[0,2],1]

array([1, 9])

In [39]:
ary[1,[0,2]]

array([4, 6])

In [163]:
ary[0][0],ary[2,2].shape

(0, ())

In [156]:
ary[[0,2],[0,2]]

array([ 0, 10])

In [151]:
ary[[0,2],[0,2]].reshape(1,2)

array([[ 0, 10]])

boolean mask를 이용한 인덱싱 
1. Ture and False 를 사용하여 만든 배열을 불리언 마스크라고한다 
2. 배열의 원소를 TRUE 가 있는 위치로 인덱싱할떄 활용한다. 

In [41]:
bool_mask = np.array([True,False,True])
print(bool_mask)
print(bool_mask.dtype)

[ True False  True]
bool


In [53]:
#0,2,4를 고르고싶을떄 
ary_2d = np.arange(0,6).reshape(2,3)
ary_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
bool_2d = (
    np.array([[True, False, True],
             [False, True, False]])
)

In [55]:
ary_2d[bool_2d]

array([0, 2, 4])

In [56]:
print(ary_2d.shape)
print(bool_2d.shape)

(2, 3)
(2, 3)


In [57]:
bool_2d = (
    np.array([[True, True, True],
             [False, False, False]])
)

In [58]:
ary_2d[bool_2d]

array([0, 1, 2])

In [60]:
bool_1d = (
    np.array([True,False])
)

In [62]:
ary_2d_0 = np.array([0,1,2])
ary_2d_1 = np.array([3,4,5])

ary_2d = np.array([ary_2d_0,ary_2d_1])
bool_1d = np.array([True,False])

In [63]:
ary_2d[bool_1d]

array([[0, 1, 2]])

인덱싱할 배열과 불리언 마스크의 원소의 개수가 서로다루다면 

In [67]:
bool_2d = (
    np.array([[True,False],
            [False, True]])
)

In [72]:
ary_3d = np.arange(24).reshape(4,2,3)
ary_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [81]:
bool_3d = (
    np.array([[[True,True,True],
              [False,False,False]],
             
             [[False,False,False],
             [True,True,True]],
             
             [[True,True,True],
              [False,False,False]],
             
             [[False,False,False],
             [True,True,True]]])

)

In [82]:
ary_3d[bool_3d]

array([ 0,  1,  2,  9, 10, 11, 12, 13, 14, 21, 22, 23])

In [84]:
bool_2d = np.array([
    [True,False],
    [False,True],
    [True,False],
    [False,True]
])

In [86]:
ary_3d[bool_2d]

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [12, 13, 14],
       [21, 22, 23]])

In [87]:
ary = np.ones(shape=(4,2,3))
ary

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [88]:
bool_mask = np.ones(shape = (4), dtype=bool)
try:
    ary[bool_mask]
    print('인덱싱 가능')
except:
    print('인덱싱 불가능')

인덱싱 가능


In [89]:
bool_mask = np.ones(shape=(4,2), dtype=bool)
try:
    ary[bool_mask]
    print('인덱싱 가능')
except:
    print("인덱싱 불가능")

인덱싱 가능


In [90]:
bool_mask = np.ones(shape=(2,3), dtype=bool)
try:
    ary[bool_mask]
    print('인덱싱 가능')
except:
    print("인덱싱 불가능")

인덱싱 불가능


In [91]:
bool_mask = np.ones(shape=(4,3), dtype=bool)
try:
    ary[bool_mask]
    print('인덱싱 가능')
except:
    print("인덱싱 불가능")

인덱싱 불가능


비교연산자를 이용한 인덱싱 

In [94]:
ary_1d = np.arange(24,step = 2)
ary_1d

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [96]:
ary_1d[ary_1d > 5]

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22])

In [98]:
ary_1d[ary_1d<= 10]

array([ 0,  2,  4,  6,  8, 10])

In [101]:
ary_2d = ary_1d.reshape(3,4)
ary_2d

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [105]:
mask_ary = ary_2d[:,2]>5
print(mask_ary)
ary_2d[ary_2d[:,2]>5]

[False  True  True]


array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [107]:
mask_ary = ary_2d % 3 == 1
ary_2d[mask_ary]

array([ 4, 10, 16, 22])

In [108]:
#비교 연산자가 적용되는 배열과 인덱싱될때의 배열의 차이 이해 
ary_2d

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [110]:
ary_2d[1,:] >= 10

array([False,  True,  True,  True])

In [112]:
#ary_2d[ary_2d[1,:]>= 10]
ary_2d[1,ary_2d[1,:]>= 10]

array([10, 12, 14])

In [117]:
print(ary_2d.shape)
print((ary_2d[1,:]>=10).shape)
print(ary_2d[1,:].shape)
#0번째부터 맞아야함 

(3, 4)
(4,)
(4,)


In [119]:
(ary_1d)< 4 | (ary_1d>= 10)

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False])

In [121]:
ary_1d[(ary_1d)< 4 | (ary_1d>= 10)]

array([0, 2])

원소의 인덱스를 가죠오는 메소드   

조건을 충족한느 원소의 인댁스 배열을 만들어 인덱싱하기   
np.where(condition)튜플자료형에서 0차원에서 인덱스 배열 을 반환한다 .  
위치정보임 True와 같이 

In [122]:
ary_1d = np.arange(0,60,10).repeat(2)
ary_1d

array([ 0,  0, 10, 10, 20, 20, 30, 30, 40, 40, 50, 50])

In [123]:
np.where(ary_1d == 30)

(array([6, 7]),)

In [152]:
ary_1d[ np.where(ary_1d == 30)]

array([30, 30])

In [153]:
np.where(ary_1d>30)

(array([ 8,  9, 10, 11]),)

In [157]:
ary_2d = ary_1d.reshape(4,3)

In [158]:
np.where(ary_2d >30)

(array([2, 3, 3, 3]), array([2, 0, 1, 2]))

In [159]:
np.where(ary_2d[:,2]>30)

(array([2, 3]),)

In [164]:
np.where(ary_2d[3,:]>= 50)
#3번째 행에서 50보다 크거ㅏㄴ 같은 원소들을 같는 열 의 위치 (1번쨰 축)

(array([1, 2]),)

In [170]:
ary_1d

array([ 0,  0, 10, 10, 20, 20, 30, 30, 40, 40, 50, 50])

In [171]:
np.where(ary_1d >30)

(array([ 8,  9, 10, 11]),)

In [172]:
np.where(ary_1d > 30, "초과","미만")

array(['미만', '미만', '미만', '미만', '미만', '미만', '미만', '미만', '초과', '초과', '초과',
       '초과'], dtype='<U2')